name: sharik
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.16
  app_settings: ^5.2.0
  image_picker: ^1.1.2
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: lemon
      fonts:
        - asset: assets/fonts/Lemon-Regular.ttf
    - family: medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf